#!/bin/bash

cd /stable-diffusion

conda init bash
conda activate ldm

python scripts/txt2img.py --prompt 'man playing theremin in hilbert space' --plms --ckpt sd-v1-4.ckpt --skip_grid --n_samples 1 

thunar /stable-diffusion/outputs/txt2img-samples/samples/

tail -f /dev/null
